/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    __test__: typeof import('./src/components/__test__.vue')['default']
    Accesso: typeof import('./src/components/Accesso.vue')['default']
    Artista: typeof import('./src/components/artista.vue')['default']
    Benvenuto: typeof import('./src/components/Benvenuto.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Modifyprofile: typeof import('./src/components/modifyprofile.vue')['default']
    Opera: typeof import('./src/components/opera.vue')['default']
    Profilo: typeof import('./src/components/profilo.vue')['default']
    Prova: typeof import('./src/components/prova.vue')['default']
    Ricerca: typeof import('./src/components/ricerca.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test__: typeof import('./src/components/test__.vue')['default']
  }
}
